#!/bin/bash

# Scale the Django app deployment to 3 replicas
kubectl scale deployment <your-deployment-name> --replicas=3

# Verify that multiple pods are running
kubectl get pods

# Perform load testing on the app using wrk
wrk -t12 -c400 -d30s http://<your-service-ip>:<your-service-port>

# Monitor resource usage
kubectl top pods